
library(readxl)
library(openxlsx)

test <- read_excel("Ask A Manager Salary Survey 2021 (Responses).xlsx")

# Eliminar espacios al inicio y al final
test$Country <- trimws(test$Country, which = c("both"))


test$Country[grepl("Australi", test$Country)]<-"Australia"
test$Country[grepl("Canad", test$Country)]<-"Canada"
test$Country[grepl("Csnada", test$Country)]<-"Canada"
test$Country[grepl("Czech", test$Country)]<-"Czech Republic"
test$Country[grepl("England", test$Country)]<-"UK"
test$Country[grepl("Japan", test$Country)]<-"Japan"
test$Country[grepl("New Z", test$Country)]<-"New Zealand" 
test$Country[grepl("NZ", test$Country)]<-"New Zealand" 
test$Country[grepl("Northern Ireland", test$Country)]<-"Northern Ireland"
test$Country[grepl("Scotland", test$Country)]<-"Scotland"
test$Country[grepl("U.K", test$Country)]<-"UK"
test$Country[grepl("U.S", test$Country)]<-"USA"
test$Country[grepl("UK", test$Country)]<-"UK"
test$Country[grepl("United K", test$Country)]<-"UK"  
test$Country[grepl("england", test$Country)]<-"UK"
test$Country[grepl("Englang", test$Country)]<-"UK"  
test$Country[grepl("Great Britain", test$Country)]<-"UK"
test$Country[grepl("ENGLAND", test$Country)]<-"UK" 
test$Country[grepl("Danmark", test$Country)]<-"Denmark"
test$Country[grepl("hong konh", test$Country)]<-"Hong Kong"  
test$Country[grepl("Italy", test$Country)]<-"Italy"
test$Country[grepl("Luxem", test$Country)]<-"Luxembourg" 
test$Country[grepl("México", test$Country)]<-"Mexico" 
test$Country[grepl("Nederland", test$Country)]<-"Netherlands" 
test$Country[grepl("NL", test$Country)]<-"Netherlands"  
test$Country[grepl("The Netherlands", test$Country)]<-"Netherlands"
test$Country[grepl("the Netherlands", test$Country)]<-"Netherlands"
test$Country[grepl("Remote", test$Country)]<-"Remote"
test$Country[grepl("Contracts", test$Country)]<-"Remote"
test$Country[grepl("Global", test$Country)]<-"Remote"
test$Country[grepl("International", test$Country)]<-"Remote"
test$Country[grepl("n/a", test$Country)]<-"Remote"
test$Country[grepl("na", test$Country)]<-"Remote"
test$Country[grepl("United S", test$Country)]<-"USA"
test$Country[grepl("US", test$Country)]<-"USA"
test$Country[grepl("U. S", test$Country)]<-"USA"
test$Country[grepl("U. S.", test$Country)]<-"USA"
test$Country[grepl("U.A.", test$Country)]<-"USA"
test$Country[grepl("u.s.", test$Country)]<-"USA"
test$Country[grepl("U.s.a.", test$Country)]<-"USA"
test$Country[grepl("UA", test$Country)]<-"USA"
test$Country[grepl("Uniited States", test$Country)]<-"USA"
test$Country[grepl("Unite States", test$Country)]<-"USA"
test$Country[grepl("United  States", test$Country)]<-"USA"
test$Country[grepl("united stated", test$Country)]<-"USA"
test$Country[grepl("United states", test$Country)]<-"USA"
test$Country[grepl("united states of america", test$Country)]<-"USA"
test$Country[grepl("United statew", test$Country)]<-"USA"
test$Country[grepl("United y", test$Country)]<-"USA"
test$Country[grepl("UnitedStates", test$Country)]<-"USA"
test$Country[grepl("Uniteed States", test$Country)]<-"USA"
test$Country[grepl("Unitef Stated", test$Country)]<-"USA"
test$Country[grepl("Uniter Statez", test$Country)]<-"USA"
test$Country[grepl("Unites States", test$Country)]<-"USA"
test$Country[grepl("Unitied States", test$Country)]<-"USA"
test$Country[grepl("Uniyed states", test$Country)]<-"USA"
test$Country[grepl("Uniyes States", test$Country)]<-"USA"
test$Country[grepl("Unted States", test$Country)]<-"USA"
test$Country[grepl("Untied States", test$Country)]<-"USA"
test$Country[grepl("us", test$Country)]<-"USA"
test$Country[grepl("Usat", test$Country)]<-"USA"
test$Country[grepl("UXZ", test$Country)]<-"USA"
test$Country[grepl("Virginia", test$Country)]<-"USA"
test$Country[grepl("America", test$Country)]<-"USA"
test$Country[grepl("ARGENTINA BUT MY ORG IS IN THAILAND", test$Country)]<-"Argentina"
test$Country[grepl("Brasil", test$Country)]<-"Brazil"
test$Country[grepl("Britain", test$Country)]<-"UK"
test$Country[grepl("California", test$Country)]<-"USA"
test$Country[grepl("Hartford", test$Country)]<-"USA"
test$Country[grepl("I.S.", test$Country)]<-"USA"
test$Country[grepl("IS", test$Country)]<-"USA"
test$Country[grepl("ISA", test$Country)]<-"USA"
test$Country[grepl("Jersey, Channel islands", test$Country)]<-"UK"
test$Country[grepl("United kingdom", test$Country)]<-"UK"
test$Country[grepl("Unites kingdom", test$Country)]<-"UK"
test$Country[grepl("San Francisco", test$Country)]<-"USA"
test$Country[grepl("Can", test$Country)]<-"Canada"
test$Country[grepl("Canda", test$Country)]<-"Canada"
test$Country[grepl("Catalonia", test$Country)]<-"Spain"
test$Country[grepl("Company in Germany. I work from Pakistan.", test$Country)]<-"Pakistan"
test$Country[grepl("america", test$Country)]<-"USA"
test$Country[grepl("U.s.", test$Country)]<-"USA"
test$Country[grepl("united states", test$Country)]<-"USA"
test$Country[grepl("united kingdom", test$Country)]<-"UK"
test$Country[grepl("Unites states", test$Country)]<-"USA"
test$Country[grepl("Us", test$Country)]<-"USA"
test$Country[grepl("uS", test$Country)]<-"USA"
test$Country[grepl("UNITED STATES", test$Country)]<-"USA"
test$Country[grepl("united States", test$Country)]<-"USA"
test$Country[grepl("UNited States", test$Country)]<-"USA"


test$Country[test$Country =="contracts"|test$Country =="we don't get raises, we get quarterly bonuses, but they periodically asses income in the area you work, so i got a raise because a 3rd party assessment showed i was paid too little for the area we were located"
              |test$Country =="global"|test$Country =="worldwide (based in us but short term trips aroudn the world)"
              |test$Country =="currently finance"|test$Country =="uxz"|test$Country =="catalonia"
              |test$Country =="$2,175.84/year is deducted for benefits"|test$Country =="uxz"|test$Country =="catalonia"
              |test$Country =="jersey, channel islands"|test$Country =="virginia"|test$Country =="catalonia"
              |test$Country =="hartford"|test$Country =="nl"|test$Country =="i.s."
              |test$Country =="remote"|test$Country =="uae"|test$Country =="bonus based on meeting yearly goals set w/ my supervisor"
              |test$Country =="is"|test$Country =="international"|test$Country =="i earn commission on sales. if i meet quota, i'm guaranteed another 16k min. last year i earned an additional 27k. it's not uncommon for people in my space to earn 100k+ after commission."
              |test$Country =="I was brought in on this salary to help with the EHR and very quickly was promoted to current position but compensation was not altered."
              |test$Country =="n/a (remote from wherever i want)"
              |test$Country =="ua"|test$Country =="y"|test$Country =="united y"
              |test$Country =="europe"|test$Country =="policy"|test$Country =="Y"
              |test$Country =="company in germany. i work from pakistan."|test$Country =="#N/D"|test$Country =="na"]<-"Remote"


#Generar xlsx con la base limpia
write.xlsx(test,file="base_limpia.xlsx", sheetName="base" )






